title:            association KerNEL
description:      "Fablab Lannion"
logo:             logo.png
disqus_shortname: fablablannion
default_bg:       laser.jpg
repository:       fablablannion/fablablannion.github.io
share:            true
readtime:         true
dropcap:          true
# Change url to your domain. Leave localhost server or blank when working locally.
# or use the hint from http://jekyllrb.com/docs/github-pages/ to keep this the same
# whether working locally or remotely. Start Jekyll with: jekyll serve --baseurl ''
static_url:       https://static.fablab-lannion.org
url:              https://fablablannion.github.io
# url:              http://127.0.0.1:4000


# Owner/author information
owner:
  name:           FabLab Lannion
  avatar:         logo.png
  email:          contact@fablab-lannion.org
  # Use the coder's toolbox at http://coderstoolbox.net/string/#!encoding=xml&action=encode&charset=us_ascii to encode your description into XML string
  description:    Le FabLab de Lannion
  # Social networking links used in footer. Update and remove as you like.
  twitter:        fablablannion
  facebook:       fablablannion
  github:         fablablannion
  # instagram:
  # For Google Authorship https://plus.google.com/authorship
  google_plus:    https://plus.google.com/+FablabLannion

# Analytics and webmaster tools stuff goes here
google_analytics:
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Links to include in footer navigation
# For external links add external: true
links:
  - title: Accueil
    url: /
    external: false
    icon: home
  - title: Galerie
    url: https://galerie.fablab-lannion.org
  - title: Archives
    url: /archives
  - title: Forum
    url: https://forum.fablab-lannion.org
    external: true
  - title: Wiki
    url: https://wiki.fablab-lannion.org
    external: true
  - title: Infos pratiques
    url: /horaires-et-acces
  - title: A propos
    url: /about



authors:
    colvert:
        name: Morgan Richomme
        function: Vice secrétaire 2016
        description:
        gravatar: 1055c2d168d9878befb9c8810eda96dc
        twitter: morganrichomme
        github: colvert
        google_plus:
    david:
        name: David Blaisonneau
        function: Trésorier 2016
        description: Make is not an alternative.
        gravatar: d6cd7628bc242b87449712f0fef53924
        twitter: davidblaisonneau
        github: davidblaisonneau
        google_plus: +DavidBlaisonneau
    theo:
        name: Théophile Paimparay
        function: Membre actif
        gravatar: 9502acf1be9fecea08fdb1baca814060
    tangi:
        name: Tangi Lavanant
        function: Secrétaire 2016
        gravatar: d04670b347e106df6309c4a3235f00b9
        github: fabtangi
    fablab:
        name: Fablab Lannion
    jerome:
        name: Jérôme Labidurie
        function: Président 2016
        gravatar: 29020340fd48c04adad04976cb909b4f
        twitter: buggerone
        github: jerome-labidurie
    laurenta:
        name: Laurent Aubertin
        function: Vice Trésorier 2016
        gravatar: 343d3f84aca2865b6af1ca90c66c6a42
    pofexpray:
        name: Nicolas Guédon
        function: Membre actif
        gravatar: 6a767bcd26d052496dac0f142243cb82
    yann:
        name: Yann
        function: Membre, ancien président 2012-2015
        gravatar: 47bb95d605c88f1038bd415412814eae
    nico:
        name: Nicolas Serre
        gravatar: 2c46b82b58bc4450c49fe66569d4c421
    yvon:
        name: Yvon Guillot
        gravatar: ae240ab5523214b3f4fad6717028461f
    cebernard:
        name: Cédric Bernard
        function: Membre actif
        gravatar: e7882ed2e25bdafbf2fef7c6643aa89f
    installparty14:
        name: Youns Bouachra
        gravatar: bfa9da2fe4514a96f1e51ef49f98676f



# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Europe/Paris
future:      true
highlighter: rouge
markdown:    kramdown
paginate:    5
paginate_path: "page:num"

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:year/:month/:slug.html

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

  coderay:
    coderay_line_numbers:
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

prose:
  rooturl: '_posts'
  siteurl: 'http://fablablannion.github.io/'
  relativeLinks: 'http://fablablannion.github.io/links.jsonp'
  media: 'images'
  metadata:
    _posts:
      - name: "published"
        field:
          label: "Published"
          element: "checkbox"
          value: "true"
      - name: "layout"
        field:
          element: "hidden"
          label: "Layout"
          value: "post"
      - name: "title"
        field:
          label: "Title"
          element: "text"
          value: "An Awesome Headline!"
      - name: "description"
        field:
          element: "text"
          label: "Description"
          placeholder: "Enter Post Description"
      - name: "headline"
        field:
          element: "text"
          label: "beadline"
          placeholder: "Enter Post Headline"
      - name: "modified"
        field:
          element: "text"
          label: "Has this page been modified?"
          placeholder: "YYYY-MM-DD"
      - name: "categories"
        field:
          element: "multiselect"
          label: "Add categories"
          placeholder: "Choose categories"
          value: personal
          options:
            - name: "Association"
              value: "association"
          alterable: true
      - name: "tags"
        field:
          element: "text"
          label: "Tags"
          placeholder: "Enter tags, separated by spaces"
      - name: "imagefeature"
        field:
          element: "text"
          label: "Featured Image"
          placeholder: "somefile.jpg"
      - name: "mathjax"
        field:
          element: "checkbox"
          label: "MathJax"
          value: false
      - name: "featured"
        field:
          element: "checkbox"
          label: "Featured?"
          value: false
      - name: "comments"
        field:
          element: "checkbox"
          label: "Comments"
          value: false

include: [".htaccess"]
exclude: ["lib", "config.rb", "Gemfile", "Capfile", "Gemfile.lock", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]
